---
title: "Análise de viagens de bicicleta na ciclovia da Av. Faria Lima, São Paulo"
author: "Vitor Aguiar"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r pkgs}
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(ggplot2)
library(scales)
library(splines)
```

```{r data}
allfiles <- list.files("../DadosDaCiclovia", recursive = TRUE, 
                       pattern = "\\d{4}-\\d{2}-\\d{2}\\.csv$", 
                       full.names = TRUE)

ciclo_df <- 
  map_df(allfiles, ~read_csv(., col_types = "---T-----")) %>%
  separate(EVENT_TIME, c("date", "time"), sep = " ") %>%
  mutate(date = as.Date(date),
         weekday = weekdays(date))

day_counts <- 
  count(ciclo_df, date, weekday) %>%
  mutate(day_class = ifelse(weekday %in% c("Saturday", "Sunday"), weekday, "weekday"))
  
hour_counts <-
  ciclo_df %>%
  separate(time, c("h", "m", "s"), sep = ":", convert = TRUE) %>%
  mutate(day_class = ifelse(weekday %in% c("Saturday", "Sunday"), weekday, "weekday")) %>%
  count(date, h, day_class)
```

```{r plot_timeseries, fig.width=8, fig.height=5}
ggplot(day_counts, aes(date, n)) +
  geom_line(size = .5, alpha = .5) +
  geom_point(aes(color = day_class), size = 1.6, alpha = .8) +
  geom_smooth(method = "loess", span = .4, se = FALSE, size = 2, color = "grey20") +
  scale_x_date(labels = date_format("%m-%Y")) +
  scale_color_manual(name = NULL,
                     values = c("weekday" = "grey35",
                                "Saturday" = "orangered3",
                                "Sunday" = "royalblue"),
                     labels = c("weekday" = "dia de semana", 
                                "Saturday" = "sábado",
                                "Sunday" = "domingo")) +
  theme_bw() +
  theme(legend.position = c(.15, .85),
        legend.margin = margin(6, 6, 6, 6),
        legend.text = element_text(size = 12)) +
  labs(x = " ", y = NULL,
       title = "Número de ciclistas por dia na ciclovia da Av. Faria Lima",
       caption = "Dados: https://github.com/LabProdam/DadosDaCiclovia")

#ggsave("../DadosDaCiclovia/plot_ciclovia.png", device = "png", height = 5, 
#       width = 8, units = "in", dpi = 300)
```

```{r plot_averages_per_hour, fig.width=8, fig.height=5}
ggplot(hour_counts, aes(h, n, fill = day_class)) +
  stat_summary(fun.y = mean, geom = "bar", alpha = .3) +
  geom_smooth(aes(color = day_class), se = FALSE,
                method = "glm",
                formula = y ~ ns(x, 9),
                method.args = list(family = gaussian(link = "log")),
                lwd = 1.5) +
  scale_x_continuous(breaks = 0:23) +
  scale_color_manual(name = NULL,
                     values = c("weekday" = "grey35",
                                "Saturday" = "orangered3",
                                "Sunday" = "royalblue"),
                     labels = c("weekday" = "dia de semana", 
                                "Saturday" = "sábado",
                                "Sunday" = "domingo")) +
    scale_fill_manual(name = NULL,
                     values = c("weekday" = "grey35",
                                "Saturday" = "orangered3",
                                "Sunday" = "royalblue"),
                     labels = c("weekday" = "dia de semana", 
                                "Saturday" = "sábado",
                                "Sunday" = "domingo")) +
  theme_bw() +
  theme(legend.position = c(.15, .83),
        legend.margin = margin(6, 6, 6, 6),
        legend.text = element_text(size = 12),
        panel.grid.major = element_line(color = "grey95"),
        panel.grid.minor = element_blank()) +
  labs(title = "Média de ciclistas por hora do dia na ciclovia da Av. Faria Lima",
       subtitle = "(Junho 2015 - Junho 2017)",
       caption = "Dados: https://github.com/LabProdam/DadosDaCiclovia",
       x = "hora", y = "média")

#ggsave("../DadosDaCiclovia/plot_ciclovia_mediaHora.png", device = "png", height = 5, 
#       width = 8, units = "in", dpi = 300)
```